# Generated by Django 3.1.5 on 2021-01-19 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=200)),
                ('tutorial_content', models.TextField()),
                ('tutorial_published', models.DateField(default=datetime.datetime(2021, 1, 19, 17, 21, 31, 312483), verbose_name='date published')),
            ],
        ),
    ]
