# Generated by Django 3.1.5 on 2021-01-19 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateField(default=datetime.datetime(2021, 1, 19, 17, 56, 54, 523323), verbose_name='date published'),
        ),
    ]
