# Generated by Django 3.1.5 on 2021-01-19 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20210119_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateField(default=datetime.datetime(2021, 1, 19, 21, 9, 36, 171922), verbose_name='date published'),
        ),
    ]
