# Generated by Django 3.1.5 on 2021-01-19 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20210119_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateField(default=datetime.datetime(2021, 1, 19, 21, 56, 23, 624976), verbose_name='date published'),
        ),
    ]
